-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-fGgFfsCxFLYZwgZxhPR7HMwnuXO2.json
-- Coach UID: fGgFfsCxFLYZwgZxhPR7HMwnuXO2
-- Generated at: 2026-04-01T21:57:14.196Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_fGgFfsCxFLYZwgZxhPR7HMwnuXO2', 'running', 'coach_uid=fGgFfsCxFLYZwgZxhPR7HMwnuXO2; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'fGgFfsCxFLYZwgZxhPR7HMwnuXO2', 'hllbsuMorm6yPZdIn9E2', 'Esteban Hernández ', 'uncle.herny326@gmail.com', '89811781', '1993-06-09'::date, 32, 110, 175, 'Pérdida de pesos', null, null, '2026-01-23T18:14:47.676Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_fGgFfsCxFLYZwgZxhPR7HMwnuXO2', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'fGgFfsCxFLYZwgZxhPR7HMwnuXO2'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
