-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-OPAc4pV0JpO2gg48mXcKr5Km0eG3.json
-- Coach UID: OPAc4pV0JpO2gg48mXcKr5Km0eG3
-- Generated at: 2026-04-01T23:59:09.221Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=OPAc4pV0JpO2gg48mXcKr5Km0eG3; clients=0; routines=0; measurements=0');




  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'OPAc4pV0JpO2gg48mXcKr5Km0eG3'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
