-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-XRlfx8WFiBVTC9Gmug3vsWbLlBJ3.json
-- Coach UID: XRlfx8WFiBVTC9Gmug3vsWbLlBJ3
-- Generated at: 2026-04-01T21:26:10.274Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_XRlfx8WFiBVTC9Gmug3vsWbLlBJ3', 'running', 'coach_uid=XRlfx8WFiBVTC9Gmug3vsWbLlBJ3; clients=2; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'XRlfx8WFiBVTC9Gmug3vsWbLlBJ3', 'DRqVRsby3c9vqcCpduuo', 'Yaudicia Sánchez ', 'y.sanchez17@hotmail.com', null, '1991-05-05'::date, 34, 54, 161, 'Ganancia muscular', null, null, '2026-01-28T16:10:38.395Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));
  perform public.migration_upsert_client('smart-coach-e479b', 'XRlfx8WFiBVTC9Gmug3vsWbLlBJ3', 'g9dM8Qqpbw5VcHnJSbkj', 'Brenda Herrera', 'bren_herrera@outlook.com', null, '1994-07-14'::date, 31, 52, 164, 'Ganancia muscular', 'Lesión cervical, no cargar peso sobre los hombros', null, '2026-01-28T15:57:44.263Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_XRlfx8WFiBVTC9Gmug3vsWbLlBJ3', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'XRlfx8WFiBVTC9Gmug3vsWbLlBJ3'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
