-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-zkabP1cthKXR6UXVwY9YHrN9Yaj1.json
-- Coach UID: zkabP1cthKXR6UXVwY9YHrN9Yaj1
-- Generated at: 2026-04-01T22:16:55.581Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=zkabP1cthKXR6UXVwY9YHrN9Yaj1; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'zkabP1cthKXR6UXVwY9YHrN9Yaj1', 'nhrlcQSpNAelLI52G3oO', 'yo', 'shaomy2007@gmail.com', null, '2007-12-18'::date, 18, 51, 160, 'ganar masa muscular', null, null, '2026-02-19T04:17:55.700Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'zkabP1cthKXR6UXVwY9YHrN9Yaj1'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
