-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-5A4NuuQ1FdMp8PQ0XuWxDhwRxgu2.json
-- Coach UID: 5A4NuuQ1FdMp8PQ0XuWxDhwRxgu2
-- Generated at: 2026-04-01T21:57:14.148Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_5A4NuuQ1FdMp8PQ0XuWxDhwRxgu2', 'running', 'coach_uid=5A4NuuQ1FdMp8PQ0XuWxDhwRxgu2; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', '5A4NuuQ1FdMp8PQ0XuWxDhwRxgu2', 'FobRuWjD8orQP6rne38c', 'Daniela Porras Valerio ', 'danielaporras191@gmail.com', '85011061', '2004-01-19'::date, 22, 64.15, 159, 'Definición muscular', 'Ninguno', null, '2026-01-23T23:41:20.192Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_5A4NuuQ1FdMp8PQ0XuWxDhwRxgu2', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', '5A4NuuQ1FdMp8PQ0XuWxDhwRxgu2'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
