-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-ptS7jAnqpwVxkruLXzIz0AKvAym2.json
-- Coach UID: ptS7jAnqpwVxkruLXzIz0AKvAym2
-- Generated at: 2026-04-01T22:13:49.012Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=ptS7jAnqpwVxkruLXzIz0AKvAym2; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'ptS7jAnqpwVxkruLXzIz0AKvAym2', 'moRRg7hzXOj8FR8ukKFt', 'Adriana Jiménez ', 'adrijimenez22@hotmail.com', '+506 8814 8030', '2026-01-15'::date, 0, 60, 1.6, 'Pérdida de peso', null, null, '2026-01-17T14:17:10.213Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'ptS7jAnqpwVxkruLXzIz0AKvAym2'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
