-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-HfbzJkwqtlQ2eSI6r0U6F2gPZCL2.json
-- Coach UID: HfbzJkwqtlQ2eSI6r0U6F2gPZCL2
-- Generated at: 2026-04-01T22:10:47.101Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=HfbzJkwqtlQ2eSI6r0U6F2gPZCL2; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'HfbzJkwqtlQ2eSI6r0U6F2gPZCL2', 'Tv359u83wjIarutcZrBr', 'Joshua Ureña Rodríguez', 'joshurena341@gmail.com', '83493607', '2006-04-19'::date, 19, 92, 180, '-', null, null, '2026-02-19T22:27:54.485Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'HfbzJkwqtlQ2eSI6r0U6F2gPZCL2'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
