-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-2v4G8e2OpSdYoFs2Wrr0r8J6voV2.json
-- Coach UID: 2v4G8e2OpSdYoFs2Wrr0r8J6voV2
-- Generated at: 2026-04-01T21:50:50.455Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_2v4G8e2OpSdYoFs2Wrr0r8J6voV2', 'running', 'coach_uid=2v4G8e2OpSdYoFs2Wrr0r8J6voV2; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', '2v4G8e2OpSdYoFs2Wrr0r8J6voV2', 'OGF84Okjpn1Ihdj9TkaI', 'José Hernández ', 'hzdvid@gmail.com', '70125433', '1991-08-21'::date, 34, 73, 172, 'Hipertrofia', null, 'San Rafael Heredia', '2026-02-17T20:56:08.504Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_2v4G8e2OpSdYoFs2Wrr0r8J6voV2', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', '2v4G8e2OpSdYoFs2Wrr0r8J6voV2'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
