-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-uehHrRK1UfPXmUKsjFzbWUhvEph1.json
-- Coach UID: uehHrRK1UfPXmUKsjFzbWUhvEph1
-- Generated at: 2026-04-01T22:16:55.544Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=uehHrRK1UfPXmUKsjFzbWUhvEph1; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'uehHrRK1UfPXmUKsjFzbWUhvEph1', 'XRB6aSks1RukeRGn62YK', 'Jocksuel', 'roynunezvillegas@gmail.com', null, '2007-02-07'::date, 18, 60, 175, 'Ganancia muscular', null, null, '2026-01-23T16:51:12.951Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'uehHrRK1UfPXmUKsjFzbWUhvEph1'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
