-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-NU1FBV9UNaa0HBzZtPEmmJUOxoy2.json
-- Coach UID: NU1FBV9UNaa0HBzZtPEmmJUOxoy2
-- Generated at: 2026-04-01T22:13:48.926Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=NU1FBV9UNaa0HBzZtPEmmJUOxoy2; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'NU1FBV9UNaa0HBzZtPEmmJUOxoy2', 'xbVMDi35UeuKwzJq8Kka', 'Marco ', 'marcocr1283@gmail.com', '71978098', '1983-06-12'::date, 42, 150, 189, 'Perdida de Peso', null, null, '2026-01-19T18:01:00.363Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'NU1FBV9UNaa0HBzZtPEmmJUOxoy2'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
