-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-S5YuIlwMxhe2Cm7UIB3P3A8s0J02.json
-- Coach UID: S5YuIlwMxhe2Cm7UIB3P3A8s0J02
-- Generated at: 2026-04-01T22:16:55.489Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=S5YuIlwMxhe2Cm7UIB3P3A8s0J02; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'S5YuIlwMxhe2Cm7UIB3P3A8s0J02', 'CFxp4vwW2uQilwwAlsNJ', 'Roger', 'jorgecb30@hotmail.com', '62184364', '1994-01-22'::date, 32, null, null, '-', null, null, '2026-01-23T01:01:05.593Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'S5YuIlwMxhe2Cm7UIB3P3A8s0J02'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
