-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-gtHClGPNobP9TDqkDSuFt4vXHnD2.json
-- Coach UID: gtHClGPNobP9TDqkDSuFt4vXHnD2
-- Generated at: 2026-04-01T22:10:47.063Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=gtHClGPNobP9TDqkDSuFt4vXHnD2; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'gtHClGPNobP9TDqkDSuFt4vXHnD2', 'QYgbNaNbS1EjGQQL1kc1', 'Brenda Brenes Gamboa', 'bgamboa26@gmail.com', '87897336', '1987-11-26'::date, 38, 55, 157, 'Ganancia de masa muscular', 'No tiene lesiones ni padecimientos', 'Turrialba', '2026-02-18T12:42:46.596Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'gtHClGPNobP9TDqkDSuFt4vXHnD2'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
