-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-PCi9WXpWN7MKGZShunrTgBLWrCp2.json
-- Coach UID: PCi9WXpWN7MKGZShunrTgBLWrCp2
-- Generated at: 2026-04-01T22:13:48.974Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=PCi9WXpWN7MKGZShunrTgBLWrCp2; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'PCi9WXpWN7MKGZShunrTgBLWrCp2', 'r6wMsCOQmEKMnneLd3ZU', 'Stefany', 'sjimenez1609@yahoo.es', '89519094', '1986-09-16'::date, 39, 54, 155, 'Gancia de masa muscular y reconstitucion', 'En la sentadilla tiene que abrir mas las rodillas con un arco plantar y consentrarse en hacer bien la tecnica y repiracion.', null, '2026-01-23T21:09:26.119Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'PCi9WXpWN7MKGZShunrTgBLWrCp2'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
