-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-n2h8GITqV6b7VzVqfzDPla3tQo63.json
-- Coach UID: n2h8GITqV6b7VzVqfzDPla3tQo63
-- Generated at: 2026-04-01T23:28:56.006Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=n2h8GITqV6b7VzVqfzDPla3tQo63; clients=0; routines=0; measurements=0');




  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'n2h8GITqV6b7VzVqfzDPla3tQo63'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
