-- Generated by scripts/build-phase3-coach-slice-migration.mjs
-- Source: docs/migrations/phase2-coach-slice-hWO7x3mkHfU4EiOGXpqKLI9ctpa2.json
-- Coach UID: hWO7x3mkHfU4EiOGXpqKLI9ctpa2
-- Generated at: 2026-04-01T22:10:47.141Z

do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase3_coach_slice_pilot', 'running', 'coach_uid=hWO7x3mkHfU4EiOGXpqKLI9ctpa2; clients=1; routines=0; measurements=0');


  perform public.migration_upsert_client('smart-coach-e479b', 'hWO7x3mkHfU4EiOGXpqKLI9ctpa2', 'MkomENBgC2ytkzFq34F6', 'Kary Lucia Torres Barroso', 'Paulacr42@gmail.com', '83245115', '2003-03-17'::date, 22, 60, 50, '-', null, null, '2026-02-04T21:34:17.138Z'::timestamptz, v_run_id, jsonb_build_object('origin', 'phase2_slice'));


  update public.migration_runs set status = 'completed', finished_at = now() where id = v_run_id;
exception
  when others then
    insert into public.migration_errors (run_id, phase, entity_type, error_code, error_message, payload) values (v_run_id, 'phase3_coach_slice_pilot', 'vertical_slice', SQLSTATE, SQLERRM, jsonb_build_object('coach_uid', 'hWO7x3mkHfU4EiOGXpqKLI9ctpa2'));
    update public.migration_runs set status = 'failed', finished_at = now(), notes = coalesce(notes, '') || ' | ' || SQLERRM where id = v_run_id;
    raise;
end $$;
