-- Generated phase4 exercises full backfill batch
do $$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.migration_runs (id, phase, status, notes) values (v_run_id, 'phase4_exercises_full_backfill', 'running', 'batch=5; rows=28');
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'nIXqpWqRF2rftG0euvuk', 'Patada de Dorso', 'Core', 'coach', 'https://youtu.be/ZB1SwBRVLCc?si=yeDL7e981WN9kbVP', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVmOWMzIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+nmDwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'nMgPYYnIfj0gClNoHzF7', 'Lagartija tocó hombro', 'Pecho', 'coach', 'https://youtube.com/shorts/a0XoLNQ8WRE?si=BMey0oh1jwF9LzFx', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVlMmUyIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'nNXlOBrY8CmoeHnouDvQ', 'Remo sentado con banda', 'Espalda', 'coach', 'https://youtu.be/KmpDowjBY2A?si=ZgN51kpv7mQaxrkT', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZGJlYWZlIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'qJKafDpIazmENRhESCc2', 'Lagartija en Bola Medicinal Individual', 'Pecho', 'coach', 'https://youtu.be/oF2dMVdvnik?si=FjJXoGOKVvIPVltU', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVlMmUyIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'qM6fL77JG6IHM9eg6fdh', 'Rebote de hombro doble', 'Hombros', 'coach', 'https://youtu.be/B9oG7ss_I78?si=090eISoZvSLIUKfd', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZlZGQ1Ii8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'qrtudywrqi3y2wa2jQfk', 'Rotación Externa con Banda', 'Hombros', 'coach', 'https://youtu.be/wQdfeB80fqo?si=M2TR8E7nJC3KUTZy', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZlZGQ1Ii8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'qylyiz1KzeLPcRf5wj6r', 'Curl Concentrado', 'Bíceps', 'coach', 'https://youtu.be/VMbDQ8PZazY?si=G1FnkXglInVhdWgn', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZGNmY2U3Ii8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'rLMtUUz4YL4u1YXKSBnV', 'Lagartija negativa', 'Pecho', 'coach', 'https://youtube.com/shorts/Gtpmsd13fjs?si=-5FNOhkTuDf-XOGL', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVlMmUyIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'sCtTA7Mhy4Odpw4wKbcY', 'Sentadillas parciales', 'Cuádriceps', 'coach', 'https://youtu.be/ktMbRDQ_7fc?si=MKbSZ0K4DDYFuuuX', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZGJlYWZlIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'sVNd5q5mTMO1G03xUYTL', 'Extensiones lumbares', 'Espalda', 'coach', 'https://youtu.be/KNBNgfdVbSQ?si=7Bhzhsl4HV9CDOZh', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZGJlYWZlIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'sZ1JU6dmZnwfKlxu6hkY', 'Elevación lateral de hombros con banda', 'Hombros', 'coach', 'https://youtube.com/shorts/__0jIbOwnfI?si=P5pn0jBSueGy_-gQ', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZlZGQ1Ii8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'uEDMqN1AnUZIIyQCac3K', 'Abdominales en bola suiza', 'Core', 'coach', 'https://youtu.be/O4d3kd1ZLyc?si=DBYxStIDVHdJ9X96', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVmOWMzIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+nmDwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'uIXw5wPNkTEve8QarEDc', 'Flexion de rodilla unilateral con bola suiza', 'Isquiotibiales', 'coach', 'https://youtu.be/1zyNfalL3qc?si=MjoIQTje4ctixx2K', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZGNmY2U3Ii8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'uy5j0abIgkHI71svQEaB', 'Remo a press con landmine', 'Full Body', 'coach', 'https://youtu.be/Y7ffMbxZBUo?si=_WQd3qYbwfLFW6gw', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZjNmNGY2Ii8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'vIhRC9Fupbcpn80cQHuM', 'Sts con brazos en elevación con banda', 'Rehabilitación', 'coach', 'https://youtu.be/HXoq7dheEEE?si=ECen1SoQd-dbNxZN', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZTVlN2ViIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+4pm/PC90ZXh0PgogICAgPC9zdmc+', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'vYSEiXGTETnSOJRj0Zfh', 'Empuje bola medicinal acostado', 'Pecho', 'coach', 'https://youtube.com/shorts/hyC1fsv-WHE?si=9Y59Mry9G52K3r_U', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVlMmUyIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'vmuh7F6552Rs8HO0s1NZ', 'Patada de Mula con banda', 'Tríceps', 'coach', 'https://youtu.be/TOfl8Gwj010?si=Dms93rXLt0nXGAw2', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZjNlOGZmIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'vqMWtXxFuAEZOK6c1o1w', 'Aperturas de pies con banda', 'Glúteos', 'coach', 'https://youtu.be/MDdcv4ITUxk?si=nIjT_SSmfIYMSrrn', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVlMmUyIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+NkTwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'wBU45B1EVxgxJHbTC01j', 'Rdl individual con landmine', 'Full Body', 'coach', 'https://youtu.be/6e0tp0_s5Zs?si=uXXvWaUgpbRicgJZ', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZjNmNGY2Ii8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'wVMtwhFOivSrIGGAysbb', 'Press de hombro con kettlebell', 'Hombros', 'coach', 'https://youtu.be/6fUrgob01UQ?si=4yjRgA82maDF9blG', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZlZGQ1Ii8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'x4101gUXbXmZ1Tlypkpt', 'Superman con bola suiza', 'Espalda', 'coach', 'https://youtu.be/8uQi9VhRUus?si=yeIz7EnjbASckNU9', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZGJlYWZlIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'xF2qULFcNwnZtSKhjhGz', 'Twist de oblicuo con landmine', 'Core', 'coach', 'https://youtu.be/epdBIT32SS0?si=u8XGSMPHRM9kG60i', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVmOWMzIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+nmDwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'xz616M3yFsXfDuSK5Sxo', 'Step up con mancuerna', 'Glúteos', 'coach', 'https://youtu.be/9ZknEYboBOQ?si=uZeMei2FS-cMifV1', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVlMmUyIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+NkTwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'yKpCQsJjrbI1lBYO8ufN', 'Abdominal en polea', 'Core', 'coach', 'https://youtu.be/ToJeyhydUxU?si=8TKD3tBv_re4eV-_', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVmOWMzIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+nmDwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'yO9lvJAHrpjD7dsi89Sd', 'Desplante lateral con landmine', 'Cuádriceps', 'coach', 'https://youtu.be/C4A6HAFXiIs?si=eYGcHz0-yjLMu8ol', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZGJlYWZlIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'yqLxnRY5AHXIMvMIKMuo', 'Flexión de bicep a press con landmine', 'Full Body', 'coach', 'https://youtube.com/shorts/B9dnsky7Z3w?si=Q4wqL5VHOhOX5_qS', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZjNmNGY2Ii8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+Pi++4jzwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'zbblXIgHOTYJwxZy1yS5', 'Step jump', 'Potencia', 'coach', 'https://youtu.be/L7e-wpka388?si=NJbcC_cSs2XtFsKU', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVmMDhhIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+4pqhPC90ZXh0PgogICAgPC9zdmc+', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  perform public.migration_upsert_exercise('smart-coach-e479b', 'tMTY6KaUczTtbloobny3gwV3eDo1', 'zyTwdIWTk3k2QBxoda8O', 'Plancha Empuje/Jalon con kettlebell', 'Core', 'coach', 'https://youtu.be/IsC1PtOs934?si=eXgNpq9jjq2f3kho', 'data:image/svg+xml;base64,CiAgICA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDEwMCAxMDAiPgogICAgICAgIDxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmVmOWMzIi8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuMzVlbSI+8J+nmDwvdGV4dD4KICAgIDwvc3ZnPg==', v_run_id, jsonb_build_object('origin','phase4_full_exercises'));
  update public.migration_runs set status='completed', finished_at=now() where id=v_run_id;
exception when others then
  update public.migration_runs set status='failed', finished_at=now(), notes=coalesce(notes,'') || ' | error=' || sqlerrm where id=v_run_id;
  raise;
end $$;
